### ISSUE TITLE
Sessions being left open with "closing session... err: EOF session not found in openRequests"

### ISSUE THREAD

**Issue by jessebye** [omrikiei/ktunnel#23]
We are using `ktunnel` to use `xdebug` against our remote php pods. It works great, but we noticed that all connections are left open indefinitely.

The `ktunnel` logs show errors that seem to be related:
```
INFO[2020-07-22 22:37:08 closing session 8b033568-e519-46ea-a42d-164b12a3c46d; err: EOF 
ERRO[2020-07-22 22:37:14 8b033568-e519-46ea-a42d-164b12a3c46d; session not found in openRequests 
ERRO[2020-07-22 22:37:15 8b033568-e519-46ea-a42d-164b12a3c46d; session not found in openRequests 
INFO[2020-07-22 22:38:02 closing session 407cef1f-3cf7-4505-83b6-4f05f665388f; err: EOF 
ERRO[2020-07-22 22:38:11 407cef1f-3cf7-4505-83b6-4f05f665388f; session not found in openRequests 
ERRO[2020-07-22 22:38:12 407cef1f-3cf7-4505-83b6-4f05f665388f; session not found in openRequests 
```

How do we resolve this?

**Comment by omrikiei** [comment]
Hello @jessebye, which version of ktunnel are you using on the cluster's end? do you instrument it with the cli?

**Comment by jessebye** [comment]
Hi @omrikiei , I was using `1.2.6`, and instrumenting it with the CLI.

**Comment by omrikiei** [comment]
Hey @jessebye, I think that the problem isn't that the connections are left open, but that there is instrumentation to close the connection that's invoked from multiple places and it yields the error - I'll try to return with additional insights soon. aside from the error messages - are you experiencing any additional impact?

**Comment by omrikiei** [comment]
Hi @jessebye, it seems that after the connection is closed on the pod, data is received from the client(dev machine) and this yields the error..

**Comment by jessebye** [comment]
@omrikiei hmm, so we are having this happen when using xdebug. The problem is that the php request never finishes, leaving a hanging xdebug connection. We have to kill the process every time before we send another request. I remember a while back you helped fix another xdebug issue; any chance you'd be willing to set up that stack again and see if you can reproduce this issue?

**Comment by jessebye** [comment]
it sounds like maybe the connection closes too soon, so the client tries to send data back to the xdebug pod after the connection is closed (possibly trying to finish the php thread?) and causes the error

**Comment by jessebye** [comment]
are there any timeouts that we might be hitting that would close the connection prematurely?

**Comment by omrikiei** [comment]
Dial timeout was increased to 500ms in version 1.2.7(found here in the releases) could you see if the issue reproduces with that one?

**Comment by jessebye** [comment]
I updated to 1.2.7, but still getting errors like this:

```
INFO[2020-07-29 17:21:09] Starting to listen on port 28688             
INFO[2020-07-29 17:21:11] Opening TCP connection on port 9000          
INFO[2020-07-29 17:21:19] closing session f356df48-9a88-4601-9b71-50c0791f56c9; err: EOF 
INFO[2020-07-29 17:21:23] closing session 4fbfc1db-36d4-4e49-8207-0536f2cf3ef0; err: EOF 
INFO[2020-07-29 17:21:30] closing session 4d78babd-102a-473b-af02-048187eceedd; err: EOF 
ERRO[2020-07-29 17:21:35] 4d78babd-102a-473b-af02-048187eceedd; session not found in openRequests 
ERRO[2020-07-29 17:21:35] 4fbfc1db-36d4-4e49-8207-0536f2cf3ef0; session not found in openRequests 
ERRO[2020-07-29 17:21:35] f356df48-9a88-4601-9b71-50c0791f56c9; session not found in openRequests 
```

I notice that adding a breakpoint will cause the "session not found in openRequests" message to appear. It seems like the session is closed when the IDE expects it to be open.

**Comment by jessebye** [comment]
Here are debug logs, if they are helpful. Local host:

```
INFO[2020-07-29 10:33:29] starting tcp tunnel from source 9000 to target 9000 
DEBU[2020-07-29 10:33:29] attempting to receive from stream            
DEBU[2020-07-29 10:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1; got session from server:  
INFO[2020-07-29 10:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1; new session; connecting to port 9000 
DEBU[2020-07-29 10:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 got 0 bytes 
DEBU[2020-07-29 10:33:49] attempting to receive from stream            
DEBU[2020-07-29 10:33:49] started reading from session c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1; got session from server: 475<?xml version="1.0" encoding="iso-8859-1"?>
<init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" fileuri="file:///app/index.php" language="PHP" xdebug:language_version="7.3.20" protocol_version="1.0" appid="182" idekey="api"><engine version="2.9.6"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[https://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2020 by Derick Rethans]]></copyright></init> 
DEBU[2020-07-29 10:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 got 480 bytes 
DEBU[2020-07-29 10:33:49] attempting to receive from stream            
DEBU[2020-07-29 10:33:49] read 37 bytes from conn on session c5366e5d-9f71-4ebc-8c32-e80a02662be1; err: <nil> 
DEBU[2020-07-29 10:33:49] locking: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:49] unlocked: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1; got session from server: 219<?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="feature_set" transaction_id="1" feature="show_hidden" success="1"></response> 
DEBU[2020-07-29 10:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 got 224 bytes 
DEBU[2020-07-29 10:33:49] attempting to receive from stream            
DEBU[2020-07-29 10:33:49] read 35 bytes from conn on session c5366e5d-9f71-4ebc-8c32-e80a02662be1; err: <nil> 
DEBU[2020-07-29 10:33:49] locking: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:49] unlocked: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1; got session from server: 217<?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="feature_set" transaction_id="2" feature="max_depth" success="1"></response> 
DEBU[2020-07-29 10:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 got 222 bytes 
DEBU[2020-07-29 10:33:49] attempting to receive from stream            
DEBU[2020-07-29 10:33:49] read 40 bytes from conn on session c5366e5d-9f71-4ebc-8c32-e80a02662be1; err: <nil> 
DEBU[2020-07-29 10:33:49] locking: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:49] unlocked: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1; got session from server: 220<?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="feature_set" transaction_id="3" feature="max_children" success="1"></response> 
DEBU[2020-07-29 10:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 got 225 bytes 
DEBU[2020-07-29 10:33:49] attempting to receive from stream            
DEBU[2020-07-29 10:33:49] read 45 bytes from conn on session c5366e5d-9f71-4ebc-8c32-e80a02662be1; err: <nil> 
DEBU[2020-07-29 10:33:49] locking: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:49] unlocked: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1; got session from server: 227<?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="feature_set" transaction_id="4" feature="extended_properties" success="1"></response> 
DEBU[2020-07-29 10:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 got 232 bytes 
DEBU[2020-07-29 10:33:49] attempting to receive from stream            
DEBU[2020-07-29 10:33:49] read 35 bytes from conn on session c5366e5d-9f71-4ebc-8c32-e80a02662be1; err: <nil> 
DEBU[2020-07-29 10:33:49] locking: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:49] unlocked: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1; got session from server: 217<?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="feature_set" transaction_id="5" feature="notify_ok" success="1"></response> 
DEBU[2020-07-29 10:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 got 222 bytes 
DEBU[2020-07-29 10:33:49] attempting to receive from stream            
DEBU[2020-07-29 10:33:49] read 46 bytes from conn on session c5366e5d-9f71-4ebc-8c32-e80a02662be1; err: <nil> 
DEBU[2020-07-29 10:33:49] locking: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:49] unlocked: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1; got session from server: 228<?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="feature_set" transaction_id="6" feature="resolved_breakpoints" success="1"></response> 
DEBU[2020-07-29 10:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 got 233 bytes 
DEBU[2020-07-29 10:33:49] attempting to receive from stream            
DEBU[2020-07-29 10:33:49] read 17 bytes from conn on session c5366e5d-9f71-4ebc-8c32-e80a02662be1; err: <nil> 
DEBU[2020-07-29 10:33:49] locking: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:49] unlocked: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1; got session from server: 192<?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="stdout" transaction_id="7" success="1"></response> 
DEBU[2020-07-29 10:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 got 197 bytes 
DEBU[2020-07-29 10:33:49] attempting to receive from stream            
DEBU[2020-07-29 10:33:49] read 12 bytes from conn on session c5366e5d-9f71-4ebc-8c32-e80a02662be1; err: <nil> 
DEBU[2020-07-29 10:33:49] locking: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:49] unlocked: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1; got session from server: 210<?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="status" transaction_id="8" status="starting" reason="ok"></response> 
DEBU[2020-07-29 10:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 got 215 bytes 
DEBU[2020-07-29 10:33:49] attempting to receive from stream            
DEBU[2020-07-29 10:33:49] read 15 bytes from conn on session c5366e5d-9f71-4ebc-8c32-e80a02662be1; err: <nil> 
DEBU[2020-07-29 10:33:49] locking: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:49] unlocked: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1; got session from server: 288<?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="step_into" transaction_id="9" status="break" reason="ok"><xdebug:message filename="file:///app/index.php" lineno="23"></xdebug:message></response> 
DEBU[2020-07-29 10:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1 got 293 bytes 
DEBU[2020-07-29 10:33:50] attempting to receive from stream            
DEBU[2020-07-29 10:33:50] read 59 bytes from conn on session c5366e5d-9f71-4ebc-8c32-e80a02662be1; err: <nil> 
DEBU[2020-07-29 10:33:50] locking: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:50] unlocked: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1; got session from server: 225<?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="eval" transaction_id="10"><property type="bool"><![CDATA[0]]></property></response> 
DEBU[2020-07-29 10:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1 got 230 bytes 
DEBU[2020-07-29 10:33:50] attempting to receive from stream            
DEBU[2020-07-29 10:33:50] read 55 bytes from conn on session c5366e5d-9f71-4ebc-8c32-e80a02662be1; err: <nil> 
DEBU[2020-07-29 10:33:50] locking: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:50] unlocked: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1; got session from server: 225<?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="eval" transaction_id="11"><property type="bool"><![CDATA[1]]></property></response> 
DEBU[2020-07-29 10:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1 got 230 bytes 
DEBU[2020-07-29 10:33:50] attempting to receive from stream            
DEBU[2020-07-29 10:33:50] read 59 bytes from conn on session c5366e5d-9f71-4ebc-8c32-e80a02662be1; err: <nil> 
DEBU[2020-07-29 10:33:50] locking: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:50] unlocked: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1; got session from server: 257<?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="eval" transaction_id="12"><property type="string" size="1" encoding="base64"><![CDATA[Xw==]]></property></response> 
DEBU[2020-07-29 10:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1 got 262 bytes 
DEBU[2020-07-29 10:33:50] attempting to receive from stream            
DEBU[2020-07-29 10:33:50] read 59 bytes from conn on session c5366e5d-9f71-4ebc-8c32-e80a02662be1; err: <nil> 
DEBU[2020-07-29 10:33:50] locking: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:50] unlocked: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1; got session from server: 261<?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="eval" transaction_id="13"><property type="string" size="4" encoding="base64"><![CDATA[ODA4MA==]]></property></response> 
DEBU[2020-07-29 10:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1 got 266 bytes 
DEBU[2020-07-29 10:33:50] attempting to receive from stream            
DEBU[2020-07-29 10:33:50] read 59 bytes from conn on session c5366e5d-9f71-4ebc-8c32-e80a02662be1; err: <nil> 
DEBU[2020-07-29 10:33:50] locking: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:50] unlocked: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1; got session from server: 265<?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="eval" transaction_id="14"><property type="string" size="7" encoding="base64"><![CDATA[L3N0YXR1cw==]]></property></response> 
DEBU[2020-07-29 10:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1 got 270 bytes 
DEBU[2020-07-29 10:33:50] attempting to receive from stream            
DEBU[2020-07-29 10:33:50] read 16 bytes from conn on session c5366e5d-9f71-4ebc-8c32-e80a02662be1; err: <nil> 
DEBU[2020-07-29 10:33:50] locking: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:50] unlocked: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1; got session from server: 281<?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="stack_get" transaction_id="15"><stack where="{main}" level="0" type="file" filename="file:///app/index.php" lineno="23"></stack></response> 
DEBU[2020-07-29 10:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1 got 286 bytes 
DEBU[2020-07-29 10:33:50] attempting to receive from stream            
DEBU[2020-07-29 10:33:50] read 10 bytes from conn on session c5366e5d-9f71-4ebc-8c32-e80a02662be1; err: <nil> 
DEBU[2020-07-29 10:33:50] locking: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:50] unlocked: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1; got session from server: 216<?xml version="1.0" encoding="iso-8859-1"?>
<stream xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" type="stdout" encoding="base64"><![CDATA[WC1Qb3dlcmVkLUJ5OiBQSFAvNy4zLjIw]]></stream>188<?xml version="1.0" encoding="iso-8859-1"?>
<stream xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" type="stdout" encoding="base64"><![CDATA[DQo=]]></stream>224<?xml version="1.0" encoding="iso-8859-1"?>
<stream xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" type="stdout" encoding="base64"><![CDATA[Q29udGVudC10eXBlOiBhcHBsaWNhdGlvbi9qc29u]]></stream>188<?xml version="1.0" encoding="iso-8859-1"?>
<stream xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" type="stdout" encoding="base64"><![CDATA[DQo=]]></stream>252<?xml version="1.0" encoding="iso-8859-1"?>
<stream xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" type="stdout" encoding="base64"><![CDATA[Q2FjaGUtQ29udHJvbDogbm8tY2FjaGUsIG5vLXN0b3JlLCBtdXN0LXJldmFsaWRhdGU=]]></stream>188<?xml version="1.0" encoding="iso-8859-1"?>
<stream xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" type="stdout" encoding="base64"><![CDATA[DQo=]]></stream>208<?xml version="1.0" encoding="iso-8859-1"?>
<stream xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" type="stdout" encoding="base64"><![CDATA[UHJhZ21hOiBuby1jYWNoZQ==]]></stream>188<?xml version="1.0" encoding="iso-8859-1"?>
<stream xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" type="stdout" encoding="base64"><![CDATA[DQo=]]></stream>200<?xml version="1.0" encoding="iso-8859-1"?>
<stream xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" type="stdout" encoding="base64"><![CDATA[RXhwaXJlczogMA==]]></stream>188<?xml version="1.0" encoding="iso-8859-1"?>
<stream xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" type="stdout" encoding="base64"><![CDATA[DQo=]]></stream>188<?xml version="1.0" encoding="iso-8859-1"?>
<stream xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" type="stdout" encoding="base64"><![CDATA[DQo=]]></stream>208<?xml version="1.0" encoding="iso-8859-1"?>
<stream xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" type="stdout" encoding="base64"><![CDATA[eyJzdGF0dXMiOiJnb29kIn0=]]></stream> 
DEBU[2020-07-29 10:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1 got 2496 bytes 
DEBU[2020-07-29 10:33:50] attempting to receive from stream            
DEBU[2020-07-29 10:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1; got session from server: 208<?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="run" transaction_id="16" status="stopping" reason="ok"></response> 
DEBU[2020-07-29 10:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1 got 213 bytes 
DEBU[2020-07-29 10:33:50] attempting to receive from stream            
DEBU[2020-07-29 10:33:50] read 10 bytes from conn on session c5366e5d-9f71-4ebc-8c32-e80a02662be1; err: <nil> 
DEBU[2020-07-29 10:33:50] locking: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:33:50] unlocked: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:34:08] read 45 bytes from conn on session c5366e5d-9f71-4ebc-8c32-e80a02662be1; err: <nil> 
DEBU[2020-07-29 10:34:08] locking: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:34:08] unlocked: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:34:14] read 45 bytes from conn on session c5366e5d-9f71-4ebc-8c32-e80a02662be1; err: <nil> 
DEBU[2020-07-29 10:34:14] locking: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:34:14] unlocked: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:34:16] read 45 bytes from conn on session c5366e5d-9f71-4ebc-8c32-e80a02662be1; err: <nil> 
DEBU[2020-07-29 10:34:16] locking: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 10:34:16] unlocked: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
```

ktunnel expose container:
```
time="2020-07-29T17:33:28Z" level=error msg="Failed getting kubernetes config: stat /.kube/config: no such file or directory"
INFO[2020-07-29 17:33:28] Starting to listen on port 28688             
INFO[2020-07-29 17:33:29] Opening TCP connection on port 9000          
DEBU[2020-07-29 17:33:49] Accepted new connection &{{0xc00032e000}}; <nil> 
DEBU[2020-07-29 17:33:49] got new session c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 17:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sending 0 bytes to client 
DEBU[2020-07-29 17:33:49] sending 0 bytes to client: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 17:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sent to client 
DEBU[2020-07-29 17:33:49] read 480 bytes from socket, err: <nil>       
DEBU[2020-07-29 17:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sending 480 bytes to client 
DEBU[2020-07-29 17:33:49] sending 480 bytes to client: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 17:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sent to client 
DEBU[2020-07-29 17:33:49] read 224 bytes from socket, err: <nil>       
DEBU[2020-07-29 17:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sending 224 bytes to client 
DEBU[2020-07-29 17:33:49] sending 224 bytes to client: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 17:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sent to client 
DEBU[2020-07-29 17:33:49] read 222 bytes from socket, err: <nil>       
DEBU[2020-07-29 17:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sending 222 bytes to client 
DEBU[2020-07-29 17:33:49] sending 222 bytes to client: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 17:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sent to client 
DEBU[2020-07-29 17:33:49] read 225 bytes from socket, err: <nil>       
DEBU[2020-07-29 17:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sending 225 bytes to client 
DEBU[2020-07-29 17:33:49] sending 225 bytes to client: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 17:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sent to client 
DEBU[2020-07-29 17:33:49] read 232 bytes from socket, err: <nil>       
DEBU[2020-07-29 17:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sending 232 bytes to client 
DEBU[2020-07-29 17:33:49] sending 232 bytes to client: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 17:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sent to client 
DEBU[2020-07-29 17:33:49] read 222 bytes from socket, err: <nil>       
DEBU[2020-07-29 17:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sending 222 bytes to client 
DEBU[2020-07-29 17:33:49] sending 222 bytes to client: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 17:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sent to client 
DEBU[2020-07-29 17:33:49] read 233 bytes from socket, err: <nil>       
DEBU[2020-07-29 17:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sending 233 bytes to client 
DEBU[2020-07-29 17:33:49] sending 233 bytes to client: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 17:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sent to client 
DEBU[2020-07-29 17:33:49] read 197 bytes from socket, err: <nil>       
DEBU[2020-07-29 17:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sending 197 bytes to client 
DEBU[2020-07-29 17:33:49] sending 197 bytes to client: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 17:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sent to client 
DEBU[2020-07-29 17:33:49] read 215 bytes from socket, err: <nil>       
DEBU[2020-07-29 17:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sending 215 bytes to client 
DEBU[2020-07-29 17:33:49] sending 215 bytes to client: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 17:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sent to client 
DEBU[2020-07-29 17:33:49] read 293 bytes from socket, err: <nil>       
DEBU[2020-07-29 17:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sending 293 bytes to client 
DEBU[2020-07-29 17:33:49] sending 293 bytes to client: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 17:33:49] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sent to client 
DEBU[2020-07-29 17:33:50] read 230 bytes from socket, err: <nil>       
DEBU[2020-07-29 17:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sending 230 bytes to client 
DEBU[2020-07-29 17:33:50] sending 230 bytes to client: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 17:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sent to client 
DEBU[2020-07-29 17:33:50] read 230 bytes from socket, err: <nil>       
DEBU[2020-07-29 17:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sending 230 bytes to client 
DEBU[2020-07-29 17:33:50] sending 230 bytes to client: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 17:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sent to client 
DEBU[2020-07-29 17:33:50] read 262 bytes from socket, err: <nil>       
DEBU[2020-07-29 17:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sending 262 bytes to client 
DEBU[2020-07-29 17:33:50] sending 262 bytes to client: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 17:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sent to client 
DEBU[2020-07-29 17:33:50] read 266 bytes from socket, err: <nil>       
DEBU[2020-07-29 17:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sending 266 bytes to client 
DEBU[2020-07-29 17:33:50] sending 266 bytes to client: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 17:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sent to client 
DEBU[2020-07-29 17:33:50] read 270 bytes from socket, err: <nil>       
DEBU[2020-07-29 17:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sending 270 bytes to client 
DEBU[2020-07-29 17:33:50] sending 270 bytes to client: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 17:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sent to client 
DEBU[2020-07-29 17:33:50] read 286 bytes from socket, err: <nil>       
DEBU[2020-07-29 17:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sending 286 bytes to client 
DEBU[2020-07-29 17:33:50] sending 286 bytes to client: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 17:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sent to client 
DEBU[2020-07-29 17:33:50] read 2496 bytes from socket, err: <nil>      
DEBU[2020-07-29 17:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sending 2496 bytes to client 
DEBU[2020-07-29 17:33:50] sending 2496 bytes to client: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 17:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sent to client 
DEBU[2020-07-29 17:33:50] read 213 bytes from socket, err: <nil>       
DEBU[2020-07-29 17:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sending 213 bytes to client 
DEBU[2020-07-29 17:33:50] sending 213 bytes to client: c5366e5d-9f71-4ebc-8c32-e80a02662be1 
DEBU[2020-07-29 17:33:50] c5366e5d-9f71-4ebc-8c32-e80a02662be1 sent to client 
DEBU[2020-07-29 17:33:50] read 0 bytes from socket, err: EOF           
INFO[2020-07-29 17:33:50] closing session c5366e5d-9f71-4ebc-8c32-e80a02662be1; err: EOF 
ERRO[2020-07-29 17:34:08] c5366e5d-9f71-4ebc-8c32-e80a02662be1; session not found in openRequests 
ERRO[2020-07-29 17:34:14] c5366e5d-9f71-4ebc-8c32-e80a02662be1; session not found in openRequests 
ERRO[2020-07-29 17:34:16] c5366e5d-9f71-4ebc-8c32-e80a02662be1; session not found in openRequests 
```

**Comment by omrikiei** [comment]
Probably a bug..
The client reader [explicitly ignores EOF errors](https://github.com/omrikiei/ktunnel/blob/v1.2.7/pkg/client/client.go#L106) on the stream and doesn't close the connection, while the server side reader [does not](https://github.com/omrikiei/ktunnel/blob/v1.2.7/pkg/server/server.go#L100)..

This seems like a small fix - I'll try to push it sooner than later

**Comment by omrikiei** [comment]
Hey @jessebye - a new beta version now signals the client when a connection is closed on the server side, I think it might solve this issue. Since it's a change on the server code - I don't think you need to do anything but try to reproduce the issue and see what happens(it will pull the latest image from quay.io), let me know if the issue persists.

**Comment by jessebye** [comment]
Still seeing this issue with the latest image, unfortunately.

**Comment by omrikiei** [comment]
Hi @jessebye - I modified the server to only close the connection if it was by a signal from the client. the fix is currently branched out to v_1_3 which I hope to release later this week. however if you'd like, you can clone build it locally and explicitly call the server version with the `-i` flag
for example:
```bash
./ktunnel expose -i quay.io/omrikiei/ktunnel:v_1_3 xdebug 9000
```

I made some tests to make sure it doesn't break anything and that debugging works but it would be great to get a validation from a real PHP app(I was using a simple hello world)

**Comment by jessebye** [comment]
Hey @omrikiei , that is looking better but we still get left with hanging connections. I made a video showing what happens:
https://d.pr/i/LAJona

Hopefully that helps explain the exact problem.

**Comment by omrikiei** [comment]
hey @jessebye, thanks for the feedback... i committed a minor fix to the branch - could you check now?

**Comment by jessebye** [comment]
Interesting, no longer see the "EOF" in the logs, but the same issue happens - the php thread never goes away on its own.

**Comment by jessebye** [comment]
Debug logs:
```
time="2020-08-03T21:10:54Z" level=error msg="Failed getting kubernetes config: stat /.kube/config: no such file or directory"
INFO[2020-08-03 21:10:54] Starting to listen on port 28688             
INFO[2020-08-03 21:10:55] Opening TCP connection on port 9000          
DEBU[2020-08-03 21:11:09] Accepted new connection &{{0xc00027e100}}; <nil> 
DEBU[2020-08-03 21:11:09] got new session 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:09] 69f32131-64b3-4b70-b06e-981da0066940 sending 0 bytes to client 
DEBU[2020-08-03 21:11:09] sending 0 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:09] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:09] read 479 bytes from socket, err: <nil>       
DEBU[2020-08-03 21:11:09] 69f32131-64b3-4b70-b06e-981da0066940 sending 479 bytes to client 
DEBU[2020-08-03 21:11:09] sending 479 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:09] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:09] read 224 bytes from socket, err: <nil>       
DEBU[2020-08-03 21:11:09] 69f32131-64b3-4b70-b06e-981da0066940 sending 224 bytes to client 
DEBU[2020-08-03 21:11:09] sending 224 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:09] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:09] read 222 bytes from socket, err: <nil>       
DEBU[2020-08-03 21:11:09] 69f32131-64b3-4b70-b06e-981da0066940 sending 222 bytes to client 
DEBU[2020-08-03 21:11:09] sending 222 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:09] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:09] read 225 bytes from socket, err: <nil>       
DEBU[2020-08-03 21:11:09] 69f32131-64b3-4b70-b06e-981da0066940 sending 225 bytes to client 
DEBU[2020-08-03 21:11:09] sending 225 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:09] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:10] read 232 bytes from socket, err: <nil>       
DEBU[2020-08-03 21:11:10] 69f32131-64b3-4b70-b06e-981da0066940 sending 232 bytes to client 
DEBU[2020-08-03 21:11:10] sending 232 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:10] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:10] read 222 bytes from socket, err: <nil>       
DEBU[2020-08-03 21:11:10] 69f32131-64b3-4b70-b06e-981da0066940 sending 222 bytes to client 
DEBU[2020-08-03 21:11:10] sending 222 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:10] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:10] read 233 bytes from socket, err: <nil>       
DEBU[2020-08-03 21:11:10] 69f32131-64b3-4b70-b06e-981da0066940 sending 233 bytes to client 
DEBU[2020-08-03 21:11:10] sending 233 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:10] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:10] read 197 bytes from socket, err: <nil>       
DEBU[2020-08-03 21:11:10] 69f32131-64b3-4b70-b06e-981da0066940 sending 197 bytes to client 
DEBU[2020-08-03 21:11:10] sending 197 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:10] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:10] read 215 bytes from socket, err: <nil>       
DEBU[2020-08-03 21:11:10] 69f32131-64b3-4b70-b06e-981da0066940 sending 215 bytes to client 
DEBU[2020-08-03 21:11:10] sending 215 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:10] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:10] read 293 bytes from socket, err: <nil>       
DEBU[2020-08-03 21:11:10] 69f32131-64b3-4b70-b06e-981da0066940 sending 293 bytes to client 
DEBU[2020-08-03 21:11:10] sending 293 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:10] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:10] read 230 bytes from socket, err: <nil>       
DEBU[2020-08-03 21:11:10] 69f32131-64b3-4b70-b06e-981da0066940 sending 230 bytes to client 
DEBU[2020-08-03 21:11:10] sending 230 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:10] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:10] read 230 bytes from socket, err: <nil>       
DEBU[2020-08-03 21:11:10] 69f32131-64b3-4b70-b06e-981da0066940 sending 230 bytes to client 
DEBU[2020-08-03 21:11:10] sending 230 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:10] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:10] read 262 bytes from socket, err: <nil>       
DEBU[2020-08-03 21:11:10] 69f32131-64b3-4b70-b06e-981da0066940 sending 262 bytes to client 
DEBU[2020-08-03 21:11:10] sending 262 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:10] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:10] read 266 bytes from socket, err: <nil>       
DEBU[2020-08-03 21:11:10] 69f32131-64b3-4b70-b06e-981da0066940 sending 266 bytes to client 
DEBU[2020-08-03 21:11:10] sending 266 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:10] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:10] read 270 bytes from socket, err: <nil>       
DEBU[2020-08-03 21:11:10] 69f32131-64b3-4b70-b06e-981da0066940 sending 270 bytes to client 
DEBU[2020-08-03 21:11:10] sending 270 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:10] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:11] read 514 bytes from socket, err: <nil>       
DEBU[2020-08-03 21:11:11] 69f32131-64b3-4b70-b06e-981da0066940 sending 514 bytes to client 
DEBU[2020-08-03 21:11:11] sending 514 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:11] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:11] read 355 bytes from socket, err: <nil>       
DEBU[2020-08-03 21:11:11] 69f32131-64b3-4b70-b06e-981da0066940 sending 355 bytes to client 
DEBU[2020-08-03 21:11:11] sending 355 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:11] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:11] read 313 bytes from socket, err: <nil>       
DEBU[2020-08-03 21:11:11] 69f32131-64b3-4b70-b06e-981da0066940 sending 313 bytes to client 
DEBU[2020-08-03 21:11:11] sending 313 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:11] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:11] read 541 bytes from socket, err: <nil>       
DEBU[2020-08-03 21:11:11] 69f32131-64b3-4b70-b06e-981da0066940 sending 541 bytes to client 
DEBU[2020-08-03 21:11:11] sending 541 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:11] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:11] read 335 bytes from socket, err: <nil>       
DEBU[2020-08-03 21:11:11] 69f32131-64b3-4b70-b06e-981da0066940 sending 335 bytes to client 
DEBU[2020-08-03 21:11:11] sending 335 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:11] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:11] read 4096 bytes from socket, err: <nil>      
INFO[2020-08-03 21:11:11] increasing buffer size to 8192               
DEBU[2020-08-03 21:11:11] read 2725 bytes from socket, err: <nil>      
DEBU[2020-08-03 21:11:11] 69f32131-64b3-4b70-b06e-981da0066940 sending 6821 bytes to client 
DEBU[2020-08-03 21:11:11] sending 6821 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:11] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:11] 69f32131-64b3-4b70-b06e-981da0066940 sending 0 bytes to client 
DEBU[2020-08-03 21:11:11] sending 0 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:11] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:11] read 8192 bytes from socket, err: <nil>      
INFO[2020-08-03 21:11:11] increasing buffer size to 16384              
DEBU[2020-08-03 21:11:11] read 16384 bytes from socket, err: <nil>     
DEBU[2020-08-03 21:11:11] 69f32131-64b3-4b70-b06e-981da0066940 sending 8192 bytes to client 
INFO[2020-08-03 21:11:11] increasing buffer size to 32768              
DEBU[2020-08-03 21:11:11] sending 24576 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:11] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:11] 69f32131-64b3-4b70-b06e-981da0066940 sending 0 bytes to client 
DEBU[2020-08-03 21:11:11] sending 0 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:11] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:11] read 360 bytes from socket, err: <nil>       
DEBU[2020-08-03 21:11:11] 69f32131-64b3-4b70-b06e-981da0066940 sending 360 bytes to client 
DEBU[2020-08-03 21:11:11] sending 360 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:11] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:11] read 8927 bytes from socket, err: <nil>      
DEBU[2020-08-03 21:11:11] 69f32131-64b3-4b70-b06e-981da0066940 sending 8927 bytes to client 
DEBU[2020-08-03 21:11:11] sending 8927 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:11] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:14] read 2709 bytes from socket, err: <nil>      
DEBU[2020-08-03 21:11:14] 69f32131-64b3-4b70-b06e-981da0066940 sending 2709 bytes to client 
DEBU[2020-08-03 21:11:14] sending 2709 bytes to client: 69f32131-64b3-4b70-b06e-981da0066940 
DEBU[2020-08-03 21:11:14] 69f32131-64b3-4b70-b06e-981da0066940 sent to client 
DEBU[2020-08-03 21:11:14] read 0 bytes from socket, err: EOF           
```

**Comment by jessebye** [comment]
@omrikiei sorry, we're still having some trouble because of this. Any idea how to resolve it?

**Comment by omrikiei** [comment]
Not yet, I'll try to continue troubleshooting in the next couple of days..

**Comment by omrikiei** [comment]
hi @jessebye, I'm finding it difficult to make time to troubleshoot and debug this issue, so it might take longer. I'm sorry :(

**Comment by omrikiei** [comment]
Hey @jessebye, v1.3.0 now released and connection terminations are handled in a more graceful manner - could you please check if the issue persists on this version?

**Comment by jessebye** [comment]
Hi @omrikiei! I just upgraded to v1.3.0 and am really pleased to say the issue is gone!
